apiVersion: v1
kind: Service
metadata:
  name: mysql-server
  namespace: bobo
spec:
  type: ClusterIP
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
      protocol: TCP
  selector:
    app: mysql-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-server
  namespace: bobo
spec:
  selector:
    matchLabels:
      app: mysql-server
  template:
    metadata:
      labels:
        app: mysql-server
    spec:
      containers:
        - image: mysql:8.0.31
          name: mysql
          resources:
          env:
            - name: MYSQL_USER
              value: mysql_user
            - name: MYSQL_PASSWORD
              value: mysql_password
            - name: MYSQL_ROOT_PASSWORD
              value: password
            - name: LANG
              value: C.UTF-8
          ports:
            - containerPort: 3306
              name: mysql
