apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonAnnotations:
  now: 2022-12-23
images:
  - name: nginx
    newName: nginx
    newTag: latest
namespace: bobo
resources:
  - deployment.yaml
  - service.yaml
configMapGenerator:
- name: my-application-properties
  files:
  - application.properties
