name: Kubernetes manifests

on:
  push:
    paths:
      - 'examples/**'
  workflow_dispatch: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1

      - name: validate manifests
        run: cue vet examples/nginx-deployment.yaml examples/nginx-deployment.cue
