name: Kubernetes manifests

on:
  push:
    paths:
      - 'examples/**'
  workflow_dispatch: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up kubectl
        uses: azure/setup-kubectl@v2

      - name: echo kubectl version
        run: kubectl version
